DROP TABLE Apartment CASCADE CONSTRAINTS;
DROP TABLE Tenant CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Maintenance CASCADE CONSTRAINTS;
DROP TABLE Audit_Tenant;


CREATE TABLE Apartment (
    apartment_id NUMBER PRIMARY KEY,
    apartment_name VARCHAR2(50),
    address VARCHAR2(100),
    num_of_rooms NUMBER,
    rent NUMBER
);

CREATE TABLE Tenant (
    house_no VARCHAR2(10) PRIMARY KEY,
    tenant_name VARCHAR2(50),
    phone_number VARCHAR2(15),
    apartment_id NUMBER,
    move_in_date DATE,
    due_amount NUMBER DEFAULT 0,
    FOREIGN KEY (apartment_id) REFERENCES Apartment(apartment_id) ON DELETE CASCADE
);

CREATE TABLE Payment (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_no VARCHAR2(10),
    payment_date DATE,
    amount_paid NUMBER,
    payment_method VARCHAR2(20),
    FOREIGN KEY (house_no) REFERENCES Tenant(house_no) ON DELETE CASCADE
);

CREATE TABLE Maintenance (
    apartment_id NUMBER,
    house_no VARCHAR2(10),
    issue_description VARCHAR2(200),
    request_date DATE,
    status VARCHAR2(20) DEFAULT 'Pending',
    PRIMARY KEY(apartment_id,house_no,request_date),
    FOREIGN KEY (apartment_id) REFERENCES Apartment(apartment_id) ON DELETE CASCADE
);


CREATE TABLE Audit_Tenant (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_no VARCHAR2(10),
    tenant_name VARCHAR2(50),
    phone_number VARCHAR2(15),
    apartment_id NUMBER,
    move_in_date DATE,
    action VARCHAR2(10),  -- 'INSERT', 'UPDATE', 'DELETE'
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



INSERT INTO Apartment VALUES (1, 'BSR Apartments', 'Chrompet', 3, 1200);
INSERT INTO Apartment VALUES (2, 'Alta Apartments', 'Kelambakkam', 2, 900);

INSERT INTO Tenant(house_no, tenant_name, phone_number, apartment_id, move_in_date) VALUES ('A1', 'Krishitha', '9876543210', 1, TO_DATE('2023-01-01', 'YYYY-MM-DD'));
INSERT INTO Tenant (house_no, tenant_name, phone_number, apartment_id, move_in_date) VALUES ('B2', 'Kamalika', '9123456789', 1, TO_DATE('2023-03-15', 'YYYY-MM-DD'));

INSERT INTO Maintenance(apartment_id,house_no,issue_description,request_date) VALUES (1,'B2', 'Leaking tap in the kitchen', TO_DATE('2023-05-05', 'YYYY-MM-DD'));
INSERT INTO Maintenance (apartment_id,house_no,issue_description,request_date) VALUES (1,'A1', 'Broken window in the living room', TO_DATE('2023-06-10', 'YYYY-MM-DD'));
COMMIT;


